PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/4e460cd4403148c71cf96ebd44aa321cd221e03e

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/904a602c74dc08a100b5c2bd490807de19e73e10) in current PX4/master (5e855c67477fe08517297a38e718ed1102536cf6)
https://github.com/PX4/NuttX/compare/904a602c74dc08a100b5c2bd490807de19e73e10...4e460cd4403148c71cf96ebd44aa321cd221e03e

4e460cd440 (HEAD, origin/master) arch/stm32: Fix nxstyle errors
324d3a89ed Revert "arch: cxd56xx: Fix the pause handler for SMP"
16436a7fb6 Revert "arch: armv7-a: Fix the pause handler for SMP"
3ba840aa27 Revert "arch: lc823450: Fix the pause handler for SMP"
37dad5dd04 Revert "arch: k210: Fix the pause handler for SMP"
b237748f50 Revert "arch: xtensa: Fix the pause handler for SMP"
6b767c6856 Revert "Update TODO regarding SMP"
c91939b5c0 Documentation: improve debugging section
9f6a43d0b0 libs: audio: libsamplerate: drop local patches
148afd9548 driver/sensors: support custom type of sensor.

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/24b6f9199af7b8d593e56e43419a39b95b85abca

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/909eff540d8004371d5838b9c0764cc753d665cf) in current PX4/master (5e855c67477fe08517297a38e718ed1102536cf6)
https://github.com/PX4/NuttX-apps/compare/909eff540d8004371d5838b9c0764cc753d665cf...24b6f9199af7b8d593e56e43419a39b95b85abca

24b6f919 (HEAD -> master, origin/master) examples/mld: Fix undefined reference to `mld_catfile'
a4ae1592 examples/i2schar: Fix the compile error
736a21f0 examples/chrono: Rename button_daemon to chrono_daemon
54d5def4 examples/chrono: Fix error: 'CONFIG_EXAMPLES_SLCD_DEVNAME' undeclared
99633aba graphics/nxwm/src/ccalibration.cxx: Fix syslog formats
4f11793e graphics/nxwm/src/ctouchscreen.cxx: Fix syslog formats
2667fb26 graphics/nxwidgets/src/cimage.cxx: Fix a syslog format
747ca594 canutils/candump/candump.c: Fix printf formats
a875ed2b Revert "Fix printf compile warning regarding time_t"
8cde672b Fix printf compile warning regarding time_t